version: '3'
services:
  backend:
    build: ./app
    container_name: backend
    #environment:
      # - FLASK_ENV=development
    restart: on-failure
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    command: python main.py
  postgres:
    container_name: database
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql