version: '3'
services:
  backend:
    build: ./backend
    container_name: backend
    #environment:
      # - FLASK_ENV=development
    restart: on-failure
    volumes:
      - ./backend:/backend
    ports:
      - "5000:5000"
    command: python main.py
  postgres:
    container_name: database
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./services/postgres/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  nginx:
    image: nginx:1.21
    container_name: webserver
    ports:
      - "443:443"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/ssl/:/etc/nginx/ssl/
      - ./frontend/dist/:/var/www/frontend/
    depends_on:
      - backend
    restart: unless-stopped
  